# Generated by Django 5.0.2 on 2025-02-14 10:09

import django.core.validators
import lectures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture', models.FileField(blank=True, null=True, upload_to='lecture_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), lectures.models.validate_file_size])),
                ('file1', models.FileField(blank=True, null=True, upload_to='lecture_resources/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='lecture_resources/')),
                ('video_duration', models.DurationField(blank=True, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
