# Generated by Django 5.0.2 on 2025-02-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
    ]
