# Generated by Django 5.0.2 on 2025-02-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('math_progress', models.FloatField()),
                ('science_progress', models.FloatField()),
                ('assignment_completion', models.FloatField()),
                ('attendance_rate', models.FloatField()),
                ('engagement_score', models.FloatField()),
                ('quiz_average', models.FloatField()),
            ],
        ),
    ]
